import type { Exercise } from './models'

export const exercises: Exercise[] = [
  // ===========================================================================
  // CHEST / PRESSING
  // ===========================================================================

  {
    id: 'incline-db-bench',
    name: 'Incline Dumbbell Bench Press',
    category: 'Press',
    equipment: 'Dumbbells',
    primaryMuscles: ['Upper chest'],
    secondaryMuscles: ['Front delts', 'Triceps'],
    goals: ['Build muscle', 'Get stronger'],
    type: 'compound',
    repRange: { min: 6, max: 10 },
    defaultSets: 3,
    movementPattern: 'horizontal-push',
    primaryAction: 'shoulder-horizontal-adduction',
  },

  {
    id: 'dumbbell-bench-press',
    name: 'Dumbbell Bench Press',
    category: 'Press',
    equipment: 'Dumbbells',
    primaryMuscles: ['Chest'],
    secondaryMuscles: ['Front delts', 'Triceps'],
    goals: ['Build muscle', 'Get stronger'],
    type: 'compound',
    repRange: { min: 6, max: 10 },
    defaultSets: 3,
    movementPattern: 'horizontal-push',
    primaryAction: 'shoulder-horizontal-adduction',
  },

  {
    id: 'incline-barbell-bench',
    name: 'Incline Barbell Bench Press',
    category: 'Press',
    equipment: 'Barbell',
    primaryMuscles: ['Upper chest'],
    secondaryMuscles: ['Front delts', 'Triceps'],
    goals: ['Build muscle', 'Get stronger'],
    type: 'compound',
    repRange: { min: 6, max: 10 },
    defaultSets: 3,
    movementPattern: 'horizontal-push',
    primaryAction: 'shoulder-horizontal-adduction',
  },

  {
    id: 'barbell-bench-press',
    name: 'Barbell Bench Press',
    category: 'Press',
    equipment: 'Barbell',
    primaryMuscles: ['Chest'],
    secondaryMuscles: ['Front delts', 'Triceps'],
    goals: ['Build muscle', 'Get stronger'],
    type: 'compound',
    repRange: { min: 5, max: 8 },
    defaultSets: 3,
    movementPattern: 'horizontal-push',
    primaryAction: 'shoulder-horizontal-adduction',
  },

  {
    id: 'decline-bench-press',
    name: 'Decline Bench Press',
    category: 'Press',
    equipment: 'Barbell',
    primaryMuscles: ['Chest'],
    secondaryMuscles: ['Triceps', 'Front delts'],
    goals: ['Build muscle', 'Get stronger'],
    type: 'compound',
    repRange: { min: 6, max: 10 },
    defaultSets: 3,
    movementPattern: 'horizontal-push',
    primaryAction: 'shoulder-horizontal-adduction',
  },

  {
    id: 'machine-chest-press',
    name: 'Machine Chest Press',
    category: 'Press',
    equipment: 'Machine',
    primaryMuscles: ['Chest'],
    secondaryMuscles: ['Front delts', 'Triceps'],
    goals: ['Build muscle', 'General fitness'],
    type: 'compound',
    repRange: { min: 8, max: 12 },
    defaultSets: 3,
    movementPattern: 'horizontal-push',
    primaryAction: 'shoulder-horizontal-adduction',
  },

  {
    id: 'low-to-high-cable-fly',
    name: 'Low-to-High Cable Fly',
    category: 'Press',
    equipment: 'Cable machine',
    primaryMuscles: ['Upper chest'],
    secondaryMuscles: ['Front delts'],
    goals: ['Build muscle'],
    type: 'isolation',
    repRange: { min: 10, max: 15 },
    defaultSets: 3,
    movementPattern: 'horizontal-push',
    primaryAction: 'shoulder-horizontal-adduction',
  },

  {
    id: 'cable-fly',
    name: 'Cable Fly',
    category: 'Isolation',
    equipment: 'Cable machine',
    primaryMuscles: ['Chest'],
    secondaryMuscles: ['Front delts'],
    goals: ['Build muscle'],
    type: 'isolation',
    repRange: { min: 10, max: 15 },
    defaultSets: 3,
    movementPattern: 'horizontal-push',
    primaryAction: 'shoulder-horizontal-adduction',
  },

  {
    id: 'pec-deck',
    name: 'Pec Deck',
    category: 'Isolation',
    equipment: 'Machine',
    primaryMuscles: ['Chest'],
    secondaryMuscles: [],
    goals: ['Build muscle'],
    type: 'isolation',
    repRange: { min: 10, max: 15 },
    defaultSets: 3,
    movementPattern: 'horizontal-push',
    primaryAction: 'shoulder-horizontal-adduction',
  },

  {
    id: 'dumbbell-fly',
    name: 'Dumbbell Fly',
    category: 'Isolation',
    equipment: 'Dumbbells',
    primaryMuscles: ['Chest'],
    secondaryMuscles: ['Front delts'],
    goals: ['Build muscle'],
    type: 'isolation',
    repRange: { min: 10, max: 15 },
    defaultSets: 3,
    movementPattern: 'horizontal-push',
    primaryAction: 'shoulder-horizontal-adduction',
  },

  {
    id: 'push-up',
    name: 'Push-up',
    category: 'Press',
    equipment: 'Bodyweight',
    primaryMuscles: ['Chest'],
    secondaryMuscles: ['Triceps', 'Front delts'],
    goals: ['Build muscle', 'General fitness'],
    type: 'compound',
    repRange: { min: 8, max: 20 },
    defaultSets: 3,
    movementPattern: 'horizontal-push',
    primaryAction: 'shoulder-horizontal-adduction',
  },

  {
    id: 'close-grip-bench',
    name: 'Close-Grip Bench Press',
    category: 'Press',
    equipment: 'Barbell',
    primaryMuscles: ['Triceps'],
    secondaryMuscles: ['Chest', 'Front delts'],
    goals: ['Build muscle', 'Get stronger'],
    type: 'compound',
    repRange: { min: 6, max: 10 },
    defaultSets: 3,
    movementPattern: 'horizontal-push',
    primaryAction: 'elbow-extension',
  },

  {
    id: 'dips',
    name: 'Dips',
    category: 'Press',
    equipment: 'Dip bars',
    primaryMuscles: ['Chest', 'Triceps'],
    secondaryMuscles: ['Front delts'],
    goals: ['Build muscle', 'Get stronger'],
    type: 'compound',
    repRange: { min: 6, max: 12 },
    defaultSets: 3,
    movementPattern: 'vertical-push',
    primaryAction: 'elbow-extension',
  },

  // ===========================================================================
  // SHOULDERS
  // ===========================================================================

  {
    id: 'dumbbell-shoulder-press',
    name: 'Dumbbell Shoulder Press',
    category: 'Press',
    equipment: 'Dumbbells',
    primaryMuscles: ['Front delts', 'Side delts'],
    secondaryMuscles: ['Triceps'],
    goals: ['Build muscle', 'Get stronger'],
    type: 'compound',
    repRange: { min: 6, max: 10 },
    defaultSets: 3,
    movementPattern: 'vertical-push',
    primaryAction: 'shoulder-flexion',
  },

  {
    id: 'machine-shoulder-press',
    name: 'Machine Shoulder Press',
    category: 'Press',
    equipment: 'Machine',
    primaryMuscles: ['Front delts', 'Side delts'],
    secondaryMuscles: ['Triceps'],
    goals: ['Build muscle', 'General fitness'],
    type: 'compound',
    repRange: { min: 8, max: 12 },
    defaultSets: 3,
    movementPattern: 'vertical-push',
    primaryAction: 'shoulder-flexion',
  },

  {
    id: 'arnold-press',
    name: 'Arnold Press',
    category: 'Press',
    equipment: 'Dumbbells',
    primaryMuscles: ['Front delts', 'Side delts'],
    secondaryMuscles: ['Triceps'],
    goals: ['Build muscle'],
    type: 'compound',
    repRange: { min: 8, max: 12 },
    defaultSets: 3,
    movementPattern: 'vertical-push',
    primaryAction: 'shoulder-flexion',
  },

  {
    id: 'cable-lateral-raise',
    name: 'Cable Lateral Raise',
    category: 'Shoulder',
    equipment: 'Cable machine',
    primaryMuscles: ['Side delts'],
    secondaryMuscles: [],
    goals: ['Build muscle'],
    type: 'isolation',
    repRange: { min: 10, max: 15 },
    defaultSets: 3,
    movementPattern: 'isolation',
    primaryAction: 'shoulder-abduction',
  },

  {
    id: 'db-lateral-raise',
    name: 'Dumbbell Lateral Raise',
    category: 'Shoulder',
    equipment: 'Dumbbells',
    primaryMuscles: ['Side delts'],
    secondaryMuscles: [],
    goals: ['Build muscle'],
    type: 'isolation',
    repRange: { min: 12, max: 20 },
    defaultSets: 3,
    movementPattern: 'isolation',
    primaryAction: 'shoulder-abduction',
  },

  {
    id: 'dumbbell-front-raise',
    name: 'Dumbbell Front Raise',
    category: 'Shoulder',
    equipment: 'Dumbbells',
    primaryMuscles: ['Front delts'],
    secondaryMuscles: [],
    goals: ['Build muscle'],
    type: 'isolation',
    repRange: { min: 10, max: 15 },
    defaultSets: 3,
    movementPattern: 'isolation',
    primaryAction: 'shoulder-flexion',
  },

  {
    id: 'rear-delt-fly',
    name: 'Rear Delt Fly',
    category: 'Shoulder',
    equipment: 'Dumbbells or cable',
    primaryMuscles: ['Rear delts'],
    secondaryMuscles: ['Mid back'],
    goals: ['Build muscle', 'General fitness'],
    type: 'isolation',
    repRange: { min: 12, max: 20 },
    defaultSets: 3,
    movementPattern: 'isolation',
    primaryAction: 'shoulder-horizontal-abduction',
  },

  {
    id: 'face-pull',
    name: 'Face Pull',
    category: 'Shoulder',
    equipment: 'Cable machine',
    primaryMuscles: ['Rear delts'],
    secondaryMuscles: ['Mid back'],
    goals: ['Build muscle', 'General fitness'],
    type: 'isolation',
    repRange: { min: 12, max: 20 },
    defaultSets: 3,
    movementPattern: 'isolation',
    primaryAction: 'shoulder-horizontal-abduction',
  },

  {
    id: 'upright-row',
    name: 'Cable Upright Row',
    category: 'Shoulder',
    equipment: 'Cable machine',
    primaryMuscles: ['Side delts'],
    secondaryMuscles: ['Traps'],
    goals: ['Build muscle'],
    type: 'compound',
    repRange: { min: 10, max: 15 },
    defaultSets: 3,
    movementPattern: 'isolation',
    primaryAction: 'shoulder-abduction',
  },

  {
    id: 'barbell-shrug',
    name: 'Barbell Shrug',
    category: 'Isolation',
    equipment: 'Barbell',
    primaryMuscles: ['Traps'],
    secondaryMuscles: [],
    goals: ['Build muscle', 'Get stronger'],
    type: 'isolation',
    repRange: { min: 8, max: 12 },
    defaultSets: 3,
    movementPattern: 'isolation',
    primaryAction: 'scapular-elevation',
  },

  // ===========================================================================
  // BACK / PULLING
  // ===========================================================================

  {
    id: 'pull-up',
    name: 'Pull-up',
    category: 'Pull',
    equipment: 'Pull-up bar',
    primaryMuscles: ['Lats'],
    secondaryMuscles: ['Biceps', 'Mid back'],
    goals: ['Build muscle', 'Get stronger', 'General fitness'],
    type: 'compound',
    repRange: { min: 5, max: 10 },
    defaultSets: 3,
    movementPattern: 'vertical-pull',
    primaryAction: 'shoulder-adduction',
  },

  {
    id: 'chin-up',
    name: 'Chin-up',
    category: 'Pull',
    equipment: 'Pull-up bar',
    primaryMuscles: ['Lats', 'Biceps'],
    secondaryMuscles: ['Mid back'],
    goals: ['Build muscle', 'Get stronger'],
    type: 'compound',
    repRange: { min: 5, max: 10 },
    defaultSets: 3,
    movementPattern: 'vertical-pull',
    primaryAction: 'shoulder-adduction',
  },

  {
    id: 'lat-pulldown',
    name: 'Lat Pulldown',
    category: 'Pull',
    equipment: 'Cable machine',
    primaryMuscles: ['Lats'],
    secondaryMuscles: ['Biceps', 'Mid back'],
    goals: ['Build muscle', 'General fitness'],
    type: 'compound',
    repRange: { min: 8, max: 12 },
    defaultSets: 3,
    movementPattern: 'vertical-pull',
    primaryAction: 'shoulder-adduction',
  },

  {
    id: 'assisted-pull-up-machine',
    name: 'Assisted Pull-up Machine',
    category: 'Pull',
    equipment: 'Machine',
    primaryMuscles: ['Lats'],
    secondaryMuscles: ['Biceps', 'Mid back'],
    goals: ['Build muscle', 'General fitness'],
    type: 'compound',
    repRange: { min: 8, max: 12 },
    defaultSets: 3,
    movementPattern: 'vertical-pull',
    primaryAction: 'shoulder-adduction',
  },

  {
    id: 'straight-arm-pulldown',
    name: 'Straight-Arm Pulldown',
    category: 'Isolation',
    equipment: 'Cable machine',
    primaryMuscles: ['Lats'],
    secondaryMuscles: [],
    goals: ['Build muscle'],
    type: 'isolation',
    repRange: { min: 10, max: 15 },
    defaultSets: 3,
    movementPattern: 'vertical-pull',
    primaryAction: 'shoulder-extension',
  },

  {
    id: 'cable-row',
    name: 'Seated Cable Row',
    category: 'Pull',
    equipment: 'Cable machine',
    primaryMuscles: ['Mid back', 'Lats'],
    secondaryMuscles: ['Biceps'],
    goals: ['Build muscle', 'Get stronger'],
    type: 'compound',
    repRange: { min: 8, max: 12 },
    defaultSets: 3,
    movementPattern: 'horizontal-pull',
    primaryAction: 'scapular-retraction',
  },

  {
    id: 'barbell-row',
    name: 'Barbell Row',
    category: 'Pull',
    equipment: 'Barbell',
    primaryMuscles: ['Mid back', 'Lats'],
    secondaryMuscles: ['Biceps'],
    goals: ['Build muscle', 'Get stronger'],
    type: 'compound',
    repRange: { min: 6, max: 10 },
    defaultSets: 3,
    movementPattern: 'horizontal-pull',
    primaryAction: 'scapular-retraction',
  },

  {
    id: 'chest-supported-row',
    name: 'Chest-Supported Row',
    category: 'Pull',
    equipment: 'Machine or dumbbells',
    primaryMuscles: ['Mid back', 'Lats'],
    secondaryMuscles: ['Biceps'],
    goals: ['Build muscle'],
    type: 'compound',
    repRange: { min: 8, max: 12 },
    defaultSets: 3,
    movementPattern: 'horizontal-pull',
    primaryAction: 'scapular-retraction',
  },

  {
    id: 'single-arm-db-row',
    name: 'Single-Arm Dumbbell Row',
    category: 'Pull',
    equipment: 'Dumbbells',
    primaryMuscles: ['Lats', 'Mid back'],
    secondaryMuscles: ['Biceps'],
    goals: ['Build muscle', 'Get stronger'],
    type: 'compound',
    repRange: { min: 8, max: 12 },
    defaultSets: 3,
    movementPattern: 'horizontal-pull',
    primaryAction: 'scapular-retraction',
  },

  // ===========================================================================
  // LOWER BODY
  // ===========================================================================

  {
    id: 'goblet-squat',
    name: 'Goblet Squat',
    category: 'Squat',
    equipment: 'Dumbbell or kettlebell',
    primaryMuscles: ['Quads'],
    secondaryMuscles: ['Glutes', 'Adductors'],
    goals: ['Build muscle', 'General fitness'],
    type: 'compound',
    repRange: { min: 8, max: 12 },
    defaultSets: 3,
    movementPattern: 'knee-dominant',
    primaryAction: 'knee-extension',
  },

  {
    id: 'barbell-back-squat',
    name: 'Barbell Back Squat',
    category: 'Squat',
    equipment: 'Barbell',
    primaryMuscles: ['Quads', 'Glutes'],
    secondaryMuscles: ['Adductors'],
    goals: ['Build muscle', 'Get stronger'],
    type: 'compound',
    repRange: { min: 5, max: 8 },
    defaultSets: 3,
    movementPattern: 'knee-dominant',
    primaryAction: 'knee-extension',
  },

  {
    id: 'front-squat',
    name: 'Barbell Front Squat',
    category: 'Squat',
    equipment: 'Barbell',
    primaryMuscles: ['Quads'],
    secondaryMuscles: ['Glutes', 'Adductors'],
    goals: ['Get stronger', 'Improve athletic performance'],
    type: 'compound',
    repRange: { min: 5, max: 8 },
    defaultSets: 3,
    movementPattern: 'knee-dominant',
    primaryAction: 'knee-extension',
  },

  {
    id: 'hack-squat',
    name: 'Hack Squat',
    category: 'Squat',
    equipment: 'Machine',
    primaryMuscles: ['Quads'],
    secondaryMuscles: ['Glutes'],
    goals: ['Build muscle'],
    type: 'compound',
    repRange: { min: 8, max: 12 },
    defaultSets: 3,
    movementPattern: 'knee-dominant',
    primaryAction: 'knee-extension',
  },

  {
    id: 'leg-press',
    name: 'Leg Press',
    category: 'Squat',
    equipment: 'Machine',
    primaryMuscles: ['Quads'],
    secondaryMuscles: ['Glutes'],
    goals: ['Build muscle', 'General fitness'],
    type: 'compound',
    repRange: { min: 8, max: 12 },
    defaultSets: 3,
    movementPattern: 'knee-dominant',
    primaryAction: 'knee-extension',
  },

  {
    id: 'dumbbell-lunge',
    name: 'Dumbbell Lunge',
    category: 'Squat',
    equipment: 'Dumbbells',
    primaryMuscles: ['Quads', 'Glutes'],
    secondaryMuscles: ['Adductors'],
    goals: ['Build muscle', 'General fitness'],
    type: 'compound',
    repRange: { min: 8, max: 12 },
    defaultSets: 3,
    movementPattern: 'knee-dominant',
    primaryAction: 'knee-extension',
  },

  {
    id: 'bulgarian-split-squat',
    name: 'Bulgarian Split Squat',
    category: 'Squat',
    equipment: 'Dumbbells or barbell',
    primaryMuscles: ['Quads', 'Glutes'],
    secondaryMuscles: ['Adductors'],
    goals: ['Build muscle', 'Get stronger'],
    type: 'compound',
    repRange: { min: 8, max: 12 },
    defaultSets: 3,
    movementPattern: 'knee-dominant',
    primaryAction: 'knee-extension',
  },

  {
    id: 'leg-extension',
    name: 'Leg Extension',
    category: 'Isolation',
    equipment: 'Machine',
    primaryMuscles: ['Quads'],
    secondaryMuscles: [],
    goals: ['Build muscle'],
    type: 'isolation',
    repRange: { min: 10, max: 15 },
    defaultSets: 3,
    movementPattern: 'isolation',
    primaryAction: 'knee-extension',
  },

  {
    id: 'romanian-deadlift',
    name: 'Romanian Deadlift',
    category: 'Hinge',
    equipment: 'Barbell or dumbbells',
    primaryMuscles: ['Hamstrings', 'Glutes'],
    secondaryMuscles: ['Back'],
    goals: ['Build muscle', 'Get stronger'],
    type: 'compound',
    repRange: { min: 8, max: 12 },
    defaultSets: 3,
    movementPattern: 'hip-hinge',
    primaryAction: 'hip-extension',
  },

  {
    id: 'barbell-deadlift',
    name: 'Barbell Deadlift',
    category: 'Hinge',
    equipment: 'Barbell',
    primaryMuscles: ['Glutes', 'Hamstrings'],
    secondaryMuscles: ['Quads', 'Back'],
    goals: ['Get stronger', 'Improve athletic performance'],
    type: 'compound',
    repRange: { min: 3, max: 6 },
    defaultSets: 3,
    movementPattern: 'hip-hinge',
    primaryAction: 'hip-extension',
  },

  {
    id: 'sumo-deadlift',
    name: 'Sumo Deadlift',
    category: 'Hinge',
    equipment: 'Barbell',
    primaryMuscles: ['Glutes', 'Quads'],
    secondaryMuscles: ['Hamstrings', 'Adductors', 'Back'],
    goals: ['Get stronger'],
    type: 'compound',
    repRange: { min: 3, max: 6 },
    defaultSets: 3,
    movementPattern: 'hip-hinge',
    primaryAction: 'hip-extension',
  },

  {
    id: 'trap-bar-deadlift',
    name: 'Trap Bar Deadlift',
    category: 'Hinge',
    equipment: 'Trap bar',
    primaryMuscles: ['Quads', 'Glutes'],
    secondaryMuscles: ['Hamstrings', 'Back'],
    goals: ['Get stronger', 'Improve athletic performance'],
    type: 'compound',
    repRange: { min: 5, max: 8 },
    defaultSets: 3,
    movementPattern: 'hip-hinge',
    primaryAction: 'hip-extension',
  },

  {
    id: 'hip-thrust',
    name: 'Barbell Hip Thrust',
    category: 'Hinge',
    equipment: 'Barbell',
    primaryMuscles: ['Glutes'],
    secondaryMuscles: ['Hamstrings'],
    goals: ['Build muscle', 'Get stronger'],
    type: 'compound',
    repRange: { min: 6, max: 10 },
    defaultSets: 3,
    movementPattern: 'hip-hinge',
    primaryAction: 'hip-extension',
  },

  {
    id: 'cable-pull-through',
    name: 'Cable Pull-Through',
    category: 'Hinge',
    equipment: 'Cable machine',
    primaryMuscles: ['Glutes'],
    secondaryMuscles: ['Hamstrings'],
    goals: ['Build muscle', 'General fitness'],
    type: 'compound',
    repRange: { min: 10, max: 15 },
    defaultSets: 3,
    movementPattern: 'hip-hinge',
    primaryAction: 'hip-extension',
  },

  {
    id: 'kettlebell-swing',
    name: 'Kettlebell Swing',
    category: 'Hinge',
    equipment: 'Kettlebell',
    primaryMuscles: ['Glutes'],
    secondaryMuscles: ['Hamstrings', 'Back'],
    goals: ['Improve athletic performance', 'General fitness'],
    type: 'compound',
    repRange: { min: 12, max: 20 },
    defaultSets: 3,
    movementPattern: 'hip-hinge',
    primaryAction: 'hip-extension',
  },

  {
    id: 'lying-leg-curl',
    name: 'Lying Leg Curl',
    category: 'Isolation',
    equipment: 'Machine',
    primaryMuscles: ['Hamstrings'],
    secondaryMuscles: [],
    goals: ['Build muscle'],
    type: 'isolation',
    repRange: { min: 10, max: 15 },
    defaultSets: 3,
    movementPattern: 'isolation',
    primaryAction: 'knee-flexion',
  },

  {
    id: 'seated-leg-curl',
    name: 'Seated Leg Curl',
    category: 'Isolation',
    equipment: 'Machine',
    primaryMuscles: ['Hamstrings'],
    secondaryMuscles: [],
    goals: ['Build muscle'],
    type: 'isolation',
    repRange: { min: 10, max: 15 },
    defaultSets: 3,
    movementPattern: 'isolation',
    primaryAction: 'knee-flexion',
  },

  {
    id: 'standing-calf-raise',
    name: 'Standing Calf Raise',
    category: 'Isolation',
    equipment: 'Machine',
    primaryMuscles: ['Calves'],
    secondaryMuscles: [],
    goals: ['Build muscle'],
    type: 'isolation',
    repRange: { min: 10, max: 15 },
    defaultSets: 4,
    movementPattern: 'isolation',
    primaryAction: 'ankle-plantarflexion',
  },

  {
    id: 'seated-calf-raise',
    name: 'Seated Calf Raise',
    category: 'Isolation',
    equipment: 'Machine',
    primaryMuscles: ['Calves'],
    secondaryMuscles: [],
    goals: ['Build muscle'],
    type: 'isolation',
    repRange: { min: 12, max: 20 },
    defaultSets: 3,
    movementPattern: 'isolation',
    primaryAction: 'ankle-plantarflexion',
  },

  {
    id: 'box-jump',
    name: 'Box Jump',
    category: 'Squat',
    equipment: 'Plyo box',
    primaryMuscles: ['Quads', 'Glutes'],
    secondaryMuscles: ['Calves'],
    goals: ['Improve athletic performance'],
    type: 'compound',
    repRange: { min: 5, max: 8 },
    defaultSets: 3,
    movementPattern: 'other',
    primaryAction: 'knee-extension',
  },

  // ===========================================================================
  // ARMS
  // ===========================================================================

  {
    id: 'dumbbell-curl',
    name: 'Dumbbell Curl',
    category: 'Arms',
    equipment: 'Dumbbells',
    primaryMuscles: ['Biceps'],
    secondaryMuscles: ['Forearms'],
    goals: ['Build muscle'],
    type: 'isolation',
    repRange: { min: 8, max: 12 },
    defaultSets: 3,
    movementPattern: 'isolation',
    primaryAction: 'elbow-flexion',
  },

  {
    id: 'ez-bar-curl',
    name: 'EZ-Bar Curl',
    category: 'Arms',
    equipment: 'EZ bar',
    primaryMuscles: ['Biceps'],
    secondaryMuscles: ['Forearms'],
    goals: ['Build muscle'],
    type: 'isolation',
    repRange: { min: 8, max: 12 },
    defaultSets: 3,
    movementPattern: 'isolation',
    primaryAction: 'elbow-flexion',
  },

  {
    id: 'hammer-curl',
    name: 'Hammer Curl',
    category: 'Arms',
    equipment: 'Dumbbells',
    primaryMuscles: ['Biceps', 'Forearms'],
    secondaryMuscles: [],
    goals: ['Build muscle'],
    type: 'isolation',
    repRange: { min: 8, max: 12 },
    defaultSets: 3,
    movementPattern: 'isolation',
    primaryAction: 'elbow-flexion',
  },

  {
    id: 'preacher-curl',
    name: 'Preacher Curl',
    category: 'Arms',
    equipment: 'Machine or EZ bar',
    primaryMuscles: ['Biceps'],
    secondaryMuscles: ['Forearms'],
    goals: ['Build muscle'],
    type: 'isolation',
    repRange: { min: 8, max: 12 },
    defaultSets: 3,
    movementPattern: 'isolation',
    primaryAction: 'elbow-flexion',
  },

  {
    id: 'cable-curl',
    name: 'Cable Curl',
    category: 'Arms',
    equipment: 'Cable machine',
    primaryMuscles: ['Biceps'],
    secondaryMuscles: ['Forearms'],
    goals: ['Build muscle'],
    type: 'isolation',
    repRange: { min: 10, max: 15 },
    defaultSets: 3,
    movementPattern: 'isolation',
    primaryAction: 'elbow-flexion',
  },

  {
    id: 'triceps-pushdown',
    name: 'Cable Triceps Pushdown',
    category: 'Arms',
    equipment: 'Cable machine',
    primaryMuscles: ['Triceps'],
    secondaryMuscles: [],
    goals: ['Build muscle'],
    type: 'isolation',
    repRange: { min: 10, max: 15 },
    defaultSets: 3,
    movementPattern: 'isolation',
    primaryAction: 'elbow-extension',
  },

  {
    id: 'overhead-triceps-extension',
    name: 'Overhead Triceps Extension',
    category: 'Arms',
    equipment: 'Dumbbell or cable',
    primaryMuscles: ['Triceps'],
    secondaryMuscles: [],
    goals: ['Build muscle'],
    type: 'isolation',
    repRange: { min: 8, max: 12 },
    defaultSets: 3,
    movementPattern: 'isolation',
    primaryAction: 'elbow-extension',
  },

  {
    id: 'skull-crusher',
    name: 'Skull Crusher',
    category: 'Arms',
    equipment: 'Barbell or EZ bar',
    primaryMuscles: ['Triceps'],
    secondaryMuscles: [],
    goals: ['Build muscle', 'Get stronger'],
    type: 'isolation',
    repRange: { min: 8, max: 12 },
    defaultSets: 3,
    movementPattern: 'isolation',
    primaryAction: 'elbow-extension',
  },

  // ===========================================================================
  // CORE / CARRIES
  // ===========================================================================

  {
    id: 'plank',
    name: 'Plank',
    category: 'Isolation',
    equipment: 'Bodyweight',
    primaryMuscles: ['Abs'],
    secondaryMuscles: [],
    goals: ['General fitness'],
    type: 'isolation',
    repRange: { min: 1, max: 1 },
    defaultSets: 3,
    movementPattern: 'isolation',
    primaryAction: 'trunk-stability',
  },

  {
    id: 'cable-crunch',
    name: 'Cable Crunch',
    category: 'Isolation',
    equipment: 'Cable machine',
    primaryMuscles: ['Abs'],
    secondaryMuscles: [],
    goals: ['Build muscle', 'General fitness'],
    type: 'isolation',
    repRange: { min: 10, max: 15 },
    defaultSets: 3,
    movementPattern: 'isolation',
    primaryAction: 'trunk-flexion',
  },

  {
    id: 'crunch-machine',
    name: 'Crunch Machine',
    category: 'Isolation',
    equipment: 'Machine',
    primaryMuscles: ['Abs'],
    secondaryMuscles: [],
    goals: ['Build muscle', 'General fitness'],
    type: 'isolation',
    repRange: { min: 10, max: 15 },
    defaultSets: 3,
    movementPattern: 'isolation',
    primaryAction: 'trunk-flexion',
  },

  {
    id: 'hanging-leg-raise',
    name: 'Hanging Leg Raise',
    category: 'Isolation',
    equipment: 'Pull-up bar',
    primaryMuscles: ['Abs'],
    secondaryMuscles: ['Hip flexors'],
    goals: ['Build muscle', 'Improve athletic performance'],
    type: 'isolation',
    repRange: { min: 8, max: 15 },
    defaultSets: 3,
    movementPattern: 'isolation',
    primaryAction: 'trunk-flexion',
  },

  {
    id: 'ab-wheel-rollout',
    name: 'Ab Wheel Rollout',
    category: 'Isolation',
    equipment: 'Ab wheel',
    primaryMuscles: ['Abs'],
    secondaryMuscles: ['Front delts'],
    goals: ['Build muscle', 'Improve athletic performance'],
    type: 'isolation',
    repRange: { min: 8, max: 15 },
    defaultSets: 3,
    movementPattern: 'isolation',
    primaryAction: 'trunk-stability',
  },

  {
    id: 'farmers-carry',
    name: "Farmer's Carry",
    category: 'Hinge',
    equipment: 'Dumbbells or kettlebells',
    primaryMuscles: ['Forearms', 'Traps'],
    secondaryMuscles: ['Abs'],
    goals: ['Improve athletic performance', 'General fitness'],
    type: 'compound',
    repRange: { min: 1, max: 1 },
    defaultSets: 3,
    movementPattern: 'carry',
    primaryAction: 'trunk-stability',
  },

  {
  id: 'hip-adduction-machine',
  name: 'Hip Adduction Machine',
  category: 'Isolation',
  equipment: 'Machine',
  primaryMuscles: ['Adductors'],
  secondaryMuscles: [],
  goals: ['Build muscle'],
  type: 'isolation',
  repRange: { min: 8, max: 15 },
  defaultSets: 3,
  movementPattern: 'isolation',
  primaryAction: 'hip-adduction',
},
{
  id: 'hip-abduction-machine',
  name: 'Hip Abduction Machine',
  category: 'Isolation',
  equipment: 'Machine',
  primaryMuscles: ['Glutes'],
  secondaryMuscles: [],
  goals: ['Build muscle'],
  type: 'isolation',
  repRange: { min: 8, max: 15 },
  defaultSets: 3,
  movementPattern: 'isolation',
  primaryAction: 'hip-abduction',
},
{
  id: 'machine-triceps-press',
  name: 'Seated Triceps Press Machine',
  category: 'Arms',
  equipment: 'Machine',
  primaryMuscles: ['Triceps'],
  secondaryMuscles: [],
  goals: ['Build muscle'],
  type: 'isolation',
  repRange: { min: 8, max: 15 },
  defaultSets: 3,
  movementPattern: 'isolation',
  primaryAction: 'elbow-extension',
},
{
  id: 'assisted-dips',
  name: 'Assisted Triceps Dip',
  category: 'Arms',
  equipment: 'Dip bars',
  primaryMuscles: ['Triceps'],
  secondaryMuscles: ['Chest', 'Front delts'],
  goals: ['Build muscle', 'Get stronger'],
  type: 'compound',
  repRange: { min: 5, max: 12 },
  defaultSets: 3,
  movementPattern: 'vertical-push',
  primaryAction: 'elbow-extension',
},
]
